version: '3.7'

services: 
  app:
    volumes:
      - static:/static
      - db:/files
    build:
      context: ../app
      args:
        PYTHON_VERSION: 3.7
    environment:
      - DOCKER=True

    ports:
      - "8000:8000"

  web:

    build:
      context: ./nginx
      args:
        NGINX_VERSION: stable
    environment:
      SSL_DOMAIN: abhedya.istenith.com
    volumes:
      - static:/static
      - letsencrypt:/etc/letsencrypt;
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on: 
      - app

volumes:
  letsencrypt:
  static:
  db:
