version: '3.7'

services: 
  app:
    volumes:
      - static:/static
      - db:/files
    build:
      context: ../app/docker
      args:
        PYTHON_VERSION: 3.7
    environment:
      - DOCKER=True

    ports: 
      - "8000:8000"

  web:

    build:
      context: ./nginx
      args:
        NGINX_VERSION: stable
    volumes:
      - static:/static
    ports:
      - "0.0.0.0:80:80"
    depends_on: 
      - app

volumes:
  static:
  db:
